### ISSUE TITLE
[Schema Inaccuracy] server-statistics missing type

### ISSUE THREAD

**Issue by jessfraz** [github/rest-api-description#1354] opened 2022-07-19 11:35 UTC
`server-statistics` looks like an object and has properties but has no `type: object`

**Comment by timrogers** [comment] 2022-07-19 11:47
@jessfraz Thanks for reporting this! I've forwarded this issue to the relevant team at GitHub.

**Comment by timrogers** [comment] 2022-07-19 14:04
@lildude 👋🏻 Would you be able to take a look at this? @erikaxu mentioned that you'd be a good person to ask.

**Comment by lildude** [comment] 2022-07-19 14:08
@timrogers sure. Can I bit a more context as the OP is a little cryptic to me.

**Comment by lildude** [comment] 2022-07-19 14:23
I spoke with @timrogers offline and I know what the issue is now.

**Comment by timrogers** [comment] 2022-07-21 11:47
@jessfraz This is actually an array of objects. This should be fixed soon 😊

**Closed** 2022-08-01 10:13 UTC
