### ISSUE TITLE
[Schema Inaccuracy] Some operations have a category of "code-scanning/

### ISSUE THREAD

**Issue by zeke** [github/rest-api-description#37] opened 2020-09-18 01:20 UTC
# Schema Inaccuracy

**Comment by xuorig** [comment] 2020-09-18 11:39
@zeke is this a duplicate of https://github.com/github/rest-api-description/issues/38? I think this is an error but feel free to reopen if that's not the case.

**Closed by xuorig** 2020-09-18 11:39 UTC
Labels: Inaccuracy

**Comment by zeke** [comment] 2020-09-18 19:34
Weird. Not sure how this happened. Yep #38 was the only issue I intended to open 👍🏼
