### ISSUE TITLE
[Schema Inaccuracy] <pagination isnt working as expected >

### ISSUE THREAD

**Issue by rtdevtest1** [github/rest-api-description#2535] opened 2023-05-18 05:01 UTC
# Schema Inaccuracy

pagination isnt working as expected

https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28#using-link-headers

This doc says "The link header will be omitted if the endpoint does not support pagination or if all results fit on a single page."

i have 2 commits and when i am trying to fetch 2 results per page, i see link header.
API used: https://api.github.com/repos/rtdevtest1/EXPLORE/commits?page=1&per_page=2&path=Explore/Versioned_Project&sha=master

## Expected

Link header shouldn't be coming in the response

## Reproduction Steps

Try to use numOfCommits = commitsRequested per_page

API used: https://api.github.com/repos/rtdevtest1/EXPLORE/commits?page=1&per_page=2&path=Explore/Versioned_Project&sha=master

$ curl -X POST https://api.github.com/issues
--->
https://api.github.com/repos/rtdevtest1/EXPLORE/commits?page=1&per_page=2&path=Explore/Versioned_Project&sha=master

**Comment by dinonuggies1** [comment] 2023-05-22 03:13
This works as intended. You've included the `per_page` query parameter which will limit the result set to the value that you specify and provide a link for the next page. If you omit the `per_page` parameter, then it should yield the results you expect under the given data conditions.

**Comment by dinonuggies1** [comment] 2023-05-22 03:34
Thanks for opening!

If you omit the `per_page` parameter, then it should yield the results you expect under the given data conditions, but to your point, when the `per_page` query parameter is included, the link header responses shouldn't include links to a second page that contains an empty set of results. This is essentially a bug.

Since this isn't a description/schema inaccuracy, I'm going to close this out and open an internal issue to investigate further 🙏🏽

**Closed by dinonuggies1** 2023-05-22 03:34 UTC

**Comment by rtdevtest1** [comment] 2023-05-22 16:56
@dinonuggies1  could you please share the bug details/ tracking for it. i would like to get updates on it, as we use this api and there's an internal bug.
