### ISSUE TITLE
[Schema Inaccuracy] lots of `type: array` missing the `items` property

### ISSUE THREAD

**Issue by jessfraz** [github/rest-api-description#453] opened 2021-07-14 21:33 UTC
# Schema Inaccuracy

## Expected

 When there is a type of an array that the items property is defined.

This is breaking some parsers. Seems like most are supposed to be strings, but would be great to make it explicit

**Comment by dinonuggies1** [comment] 2021-08-10 02:56
This issue appears to be a duplicate of https://github.com/github/rest-api-description/issues/158

**Closed** 2021-11-02 20:41 UTC
Labels: inaccuracy, P1
